Repository duplocloud/duploctl, pull requests merged in 2024-03, with the labels that each got.

#37 default tenant to none so env var is used
  .github/workflows/publish.yml
  src/duplocloud/args.py
  src/duplocloud/config.py
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#39 Ecs_service
  pyproject.toml
  src/duplo_resource/ecs_service.py
  src/duplocloud/args.py
  src/duplocloud/client.py
  src/duplocloud/config.py
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#38 k8s and aws caches creds now too
  src/duplo_resource/jit.py
  src/duplocloud/config.py
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#36 billing command
  src/duplo_resource/system.py
  src/duplo_resource/tenant.py
Labels: enhancement, Review effort [1-5]: 2

#40 aws and k8s config fun
  src/duplo_resource/jit.py
  src/duplocloud/config.py
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#41 reverted the config class
  src/duplo_resource/jit.py
  src/duplocloud/client.py
  src/duplocloud/client_test.py
  src/duplocloud/config.py
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#42 Duplo 14517
  .gitignore
  src/duplo_resource/service.py
  src/duplocloud/args.py
  src/tests/test_client.py
  src/tests/test_commander.py
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#43 add new function in service for updating replicas
  CONTRIBUTING.md
  src/duplo_resource/service.py
  src/duplocloud/args.py
  src/tests/test_client.py
  src/tests/test_commander.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#44 Pyinstaller Package
  .github/workflows/installer.yml
  .github/workflows/publish.yml
  CONTRIBUTING.md
  cli.spec
  pyproject.toml
Labels: enhancement, Review effort [1-5]: 2

#45 Pyinstaller
  .github/workflows/installer.yml
  .github/workflows/publish.yml
Labels: enhancement, Review effort [1-5]: 2

#46 Pyinstaller
  .github/workflows/installer.yml
  .github/workflows/test.yml
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#47 Releaser
  .github/workflows/image.yml
  .github/workflows/installer.yml
  .gitignore
Labels: enhancement, Review effort [1-5]: 2

#49 let it run manually to debug
  .github/workflows/release.yml
Labels: enhancement, Review effort [1-5]: 2

#50 Releaser
  .github/workflows/installer.yml
  installer.spec
Labels: enhancement, Review effort [1-5]: 2

#52 fixed issues with aks jit
  .github/workflows/image.yml
  .github/workflows/test.yml
  installer.spec
  src/duplo_resource/jit.py
  src/duplocloud/client.py
Labels: enhancement, Review effort [1-5]: 2

#53 add checksums and common release names
  .github/workflows/installer.yml
  .github/workflows/release.yml
Labels: enhancement, Review effort [1-5]: 2

#54 Releaser
  .github/workflows/version.yml
Labels: enhancement

#51 Duplo-14642
  pyproject.toml
  src/duplo_resource/job.py
  src/duplo_resource/lambda.py
  src/duplo_resource/tenant.py
Labels: enhancement, Review effort [1-5]: 2

#56 Releaser
  .github/workflows/release.yml
  .github/workflows/test.yml
  src/duplo_resource/service.py
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#57 Releaser
  .github/workflows/image.yml
  .github/workflows/installer.yml
  .github/workflows/package.yml
Labels: enhancement, Review effort [1-5]: 2

#58 config and delete on tenants
  .github/workflows/publish.yml
  .github/workflows/test_integration.yml
  .github/workflows/test_unit.yml
  pyproject.toml
  scripts/clean.sh
  src/duplo_resource/infrastructure.py
  src/duplo_resource/tenant.py
  src/duplocloud/args.py
  src/duplocloud/client.py
  src/duplocloud/resource.py
  src/tests/test_client.py
  src/tests/test_commander.py
  src/tests/test_infra.py
  src/tests/test_tenant.py
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#59 Integration tests
  src/duplo_resource/infrastructure.py
  src/duplocloud/errors.py
  src/duplocloud/resource.py
  src/tests/test_infra.py
  src/tests/test_tenant.py
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#60 Homebrew Releaser
  .github/workflows/homebrew.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  scripts/formula.py
  scripts/formula.rb.tpl
  src/tests/test_infra.py
  src/tests/test_tenant.py
Labels: enhancement, Review effort [1-5]: 2, tests

#62 Duploctl System Info Testing
  src/tests/test_portal.py
Labels: Review effort [1-5]: 2, tests

#63 v3 Tenant Resources
  pyproject.toml
  scripts/formula.py
  src/duplo_resource/cronjob.py
  src/duplo_resource/jit.py
  src/duplocloud/args.py
  src/duplocloud/client.py
  src/duplocloud/resource.py
  src/tests/conftest.py
  src/tests/data/cronjob.yaml
  src/tests/helpers.py
  src/tests/test_cronjobs.py
  src/tests/test_infra.py
  src/tests/test_tenant.py
Labels: enhancement, Review effort [1-5]: 2

#64 Integration tests
  .github/workflows/homebrew.yml
  .github/workflows/installer.yml
  .github/workflows/release.yml
  .github/workflows/test_integration.yml
  CONTRIBUTING.md
  pyproject.toml
  scripts/clean.sh
  scripts/formula.py
  scripts/formula.tpl.rb
  scripts/installer.spec
  src/duplo_resource/configmap.py
  src/duplo_resource/cronjob.py
  src/duplo_resource/job.py
  src/duplo_resource/secret.py
  src/duplocloud/cli.py
  src/duplocloud/resource.py
  src/tests/conftest.py
  src/tests/data/configmap.yaml
  src/tests/data/job.yaml
  src/tests/data/secret.yaml
  src/tests/helpers.py
  src/tests/test_cronjobs.py
  src/tests/test_infra.py
  src/tests/test_tenant.py
  src/tests/test_tenant_resources.py
Labels: documentation, enhancement, bug_fix, Review effort [1-5]: 3, tests

#65 crud for asg and hosts
  .gitignore
  CONTRIBUTING.md
  pyproject.toml
  scripts/formula.py
  src/duplo_resource/asg.py
  src/duplo_resource/hosts.py
  src/duplo_resource/lambda.py
  src/duplo_resource/tenant.py
  src/duplocloud/client.py
  src/tests/conftest.py
  src/tests/data/asg.yaml
  src/tests/data/hosts.yaml
  src/tests/data/lambda.yaml
  src/tests/data/tenant.yaml
  src/tests/test_cronjobs.py
  src/tests/test_infra.py
  src/tests/test_tenant_resources.py
Labels: enhancement, Review effort [1-5]: 4, bug_fix
