Repository duplocloud/duploctl, pull requests merged in 2024-01, with the labels that each got.

#19 DUPLO-13421_Resource-as-functions_Kelly-Ferrone
  README.md
  pyproject.toml
  src/duplo_resource/version.py
  src/duplocloud/args.py
  src/duplocloud/cli.py
  src/duplocloud/client.py
  src/duplocloud/commander.py
  src/duplocloud/resource.py
Labels: enhancement

#22 Added update_s3 command to update zip-based lambdas
  src/duplo_resource/lambda.py
Labels: enhancement, Review effort [1-5]: 2

#23 Add args required for new lambda update_s3 command
  src/duplocloud/args.py
Labels: enhancement, Review effort [1-5]: 1
