Repository duplocloud/duploctl, pull requests merged in 2024-02, with the labels that each got.

#25 DUPLO-13765_Global-Skeleton-file-argument_Kelly-Ferrone
  pyproject.toml
  src/duplo_resource/tenant.py
  src/duplocloud/argaction.py
  src/duplocloud/args.py
  src/duplocloud/argtype.py
Labels: enhancement, Review effort [1-5]: 2

#27 Create a Lambda
  src/duplo_resource/lambda.py
  src/duplo_resource/tenant.py
  src/duplocloud/args.py
Labels: enhancement

#29 official duplo config for portal context
  src/duplocloud/client.py
  src/duplocloud/commander.py
Labels: enhancement, Review effort [1-5]: 2

#28 update kubeconfig
  pyproject.toml
  src/duplo_resource/infrastructure.py
  src/duplo_resource/jit.py
  src/duplo_resource/system.py
Labels: enhancement, Review effort [1-5]: 4

#31 found all the places needing response.json()
  src/duplo_resource/cronjob.py
  src/duplo_resource/ingress.py
  src/duplo_resource/jit.py
  src/duplo_resource/lambda.py
  src/duplo_resource/service.py
  src/duplo_resource/user.py
  src/duplo_resource/version.py
Labels: enhancement, Review effort [1-5]: 2

#32 Add some simplified usage instructions with examples
  README.md
Labels: documentation, Review effort [1-5]: 1
