Repository duplocloud/duploctl, pull requests merged in 2024-07, with the labels that each got.

#81 method update - update_aws_config
  src/duplo_resource/jit.py
Labels: enhancement, Review effort [1-5]: 2, no changelog

#85 Doc updates
  .github/workflows/installer.yml
  .github/workflows/mac_runner.yml
  .github/workflows/publish.yml
  .gitignore
  CHANGELOG.md
  CONTRIBUTING.md
  mkdocs.yml
  scripts/formula.tpl.rb
  scripts/mkdocs.py
  src/duplo_resource/asg.py
  src/duplo_resource/hosts.py
  src/duplo_resource/lambda.py
  src/duplo_resource/rds.py
  src/duplo_resource/storageclass.py
  src/duplo_resource/system.py
  src/duplo_resource/user.py
  src/duplocloud/commander.py
  src/tests/data/persistentvolumeclaim.yaml
  src/tests/data/user.yaml
Labels: documentation, enhancement, Review effort [1-5]: 4

#87 Doc update
  CHANGELOG.md
  src/duplo_resource/service.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#88 Plan-resource
  CHANGELOG.md
  mkdocs.yml
  pyproject.toml
  src/duplo_resource/plan.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#89 Plan resource
  CHANGELOG.md
  mkdocs.yml
  pyproject.toml
  src/duplo_resource/jit.py
  src/duplo_resource/plan.py
Labels: documentation, enhancement, Review effort [1-5]: 3
