Repository duplocloud/duploctl, pull requests merged in 2024-05, with the labels that each got.

#75 Added support for user creation and deletion
  CHANGELOG.md
  src/duplo_resource/user.py
  src/tests/data/create-admin-user.yaml
  src/tests/data/create-non-admin-user.yaml
Labels: enhancement, Review effort [1-5]: 2, tests

#76 Feature/duplo 17490
  src/duplo_resource/hosts.py
Labels: enhancement, Review effort [1-5]: 3

#78 new pr flow
  .github/workflows/pull_request.yml
  .github/workflows/test_unit.yml
  CHANGELOG.md
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#79 server version
  CHANGELOG.md
  src/duplo_resource/version.py
Labels: documentation, enhancement, Review effort [1-5]: 2
