Repository duplocloud/duploctl, pull requests merged in 2024-08, with the labels that each got.

#91 update client error handling to print docstrings on error
  CHANGELOG.md
  src/duplocloud/client.py
Labels: enhancement, Review effort [1-5]: 2, error handling

#86 DUPLO-19210: Tenant Start/Stop Commands
  CHANGELOG.md
  src/duplo_resource/rds.py
  src/duplo_resource/tenant.py
  src/duplocloud/args.py
Labels: enhancement, Review effort [1-5]: 3

#93 apply method and some docs
  CHANGELOG.md
  src/duplo_resource/service.py
  src/duplocloud/resource.py
Labels: documentation, enhancement, Review effort [1-5]: 3

#100 configmaps and secrets from files and literals
  CHANGELOG.md
  Dockerfile
  docker-compose.yaml
  scripts/setup.sh
  src/duplo_resource/configmap.py
  src/duplo_resource/secret.py
  src/duplocloud/args.py
  src/duplocloud/argtype.py
  src/tests/files/password.txt
  src/tests/test_commander.py
Labels: enhancement, Review effort [1-5]: 3, tests
