Repository duplocloud/duploctl, pull requests merged in 2024-04, with the labels that each got.

#67 expiration format issue fix
  src/duplo_resource/jit.py
Labels: enhancement, Review effort [1-5]: 2

#68 Setter args
  .github/workflows/publish.yml
  .github/workflows/test_integration.yml
  CHANGELOG.md
  pyproject.toml
  scripts/aws_cleanup.sh
  src/duplo_resource/asg.py
  src/duplo_resource/ecs_service.py
  src/duplo_resource/hosts.py
  src/duplo_resource/infrastructure.py
  src/duplo_resource/ingress.py
  src/duplo_resource/jit.py
  src/duplo_resource/job.py
  src/duplo_resource/lambda.py
  src/duplo_resource/pod.py
  src/duplo_resource/rds.py
  src/duplo_resource/service.py
  src/duplo_resource/tenant.py
  src/duplocloud/args.py
  src/duplocloud/argtype.py
  src/duplocloud/cli.py
  src/duplocloud/client.py
  src/duplocloud/commander.py
  src/duplocloud/resource.py
  src/tests/data/job.yaml
  src/tests/data/rds-read.yaml
  src/tests/data/rds.yaml
  src/tests/data/service.yaml
  src/tests/test_infra.py
  src/tests/test_tenant.py
  src/tests/test_tenant_resources.py
Labels: enhancement, Review effort [1-5]: 4, bug_fix

#69 added changelogger
  .github/actions/setup/action.yml
  .github/workflows/image.yml
  .github/workflows/installer.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/test_integration.yml
  .github/workflows/test_unit.yml
  .gitignore
  CHANGELOG.md
  pyproject.toml
  scripts/version.py
  src/duplo_resource/service.py
Labels: documentation, enhancement, Review effort [1-5]: 2

#71 Feature/duplo 16926
  CHANGELOG.md
  pyproject.toml
  src/duplo_resource/s3.py
  src/tests/data/s3.yaml
Labels: enhancement, Review effort [1-5]: 2

#70 fix azure wait and allow tenant_id global arg
  CHANGELOG.md
  src/duplo_resource/asg.py
  src/duplo_resource/hosts.py
  src/duplo_resource/jit.py
  src/duplo_resource/job.py
  src/duplo_resource/lambda.py
  src/duplo_resource/service.py
  src/duplo_resource/tenant.py
  src/duplocloud/args.py
  src/duplocloud/client.py
  src/duplocloud/resource.py
  src/tests/conftest.py
  src/tests/test_jit.py
  src/tests/test_tenant.py
  src/tests/test_tenant_resources.py
Labels: enhancement, Review effort [1-5]: 2, bug_fix

#74 Feature/duplo 16986
  CHANGELOG.md
  pyproject.toml
  src/duplo_resource/pvc.py
  src/duplo_resource/storageclass.py
  src/tests/data/pvc.yaml
  src/tests/data/storageclass.yaml
Labels: enhancement, Review effort [1-5]: 2
