Repository duplocloud/duploctl, pull requests merged in 2025-03, with the labels that each got.

#127 missing agentplatform key
  CHANGELOG.md
  src/duplo_resource/service.py
Labels: Review effort 1/5

#132 Support init container images
  CHANGELOG.md
  CONTRIBUTING.md
  pyproject.toml
  src/duplo_resource/service.py
  src/duplocloud/args.py
  src/tests/test_service_update_image.py
Labels: Review effort 3/5

#134 DUPLO-30572: Added few unit tests for service
  CHANGELOG.md
  src/tests/test_service.py
Labels: Review effort 1/5

#135 DUPLO-30573: Added integration tests for ASG
  CHANGELOG.md
  src/tests/test_asg.py
Labels: Review effort 2/5

#136 DUPLO-30601: Added integration tests for AWS Secret
  CHANGELOG.md
  src/duplo_resource/aws_secret.py
  src/tests/test_aws_secret.py
Labels: Review effort 2/5

#133 Patch config file into test_at_least_host.
  CHANGELOG.md
  src/tests/test_client.py
Labels: Review effort 1/5

#138 DUPLO-30659: Enhanced configmap commands
  CHANGELOG.md
  src/duplo_resource/configmap.py
  src/tests/test_configmap.py
Labels: Review effort 2/5
