Repository duplocloud/duploctl, pull requests merged in 2025-07, with the labels that each got.

#156 Make AWS Secrets like K8s Secrets
  CHANGELOG.md
  src/duplo_resource/aws_secret.py
  src/duplo_resource/secret.py
  src/duplo_resource/ssm_param.py
  src/duplocloud/args.py
  src/duplocloud/argtype.py
  src/tests/data/awssecret.yaml
  src/tests/files/some-config.json
Labels: Review effort 3/5

#157 DUPLO-32863: Enhance ecs update_image to target specific container
  CHANGELOG.md
  src/duplo_resource/ecs_service.py
  src/tests/test_ecs_service.py
  src/tests/test_utils.py
Labels: Review effort 3/5

#166 Batch Job Def fixes for deprecated vcpu/memory assignment
  CHANGELOG.md
  src/duplo_resource/batch_definition.py
Labels: Review effort 3/5

#164 DUPLO-34392: Updated duploctl jit update_aws_config to overwrite existing profile
  CHANGELOG.md
  src/duplo_resource/jit.py
  src/tests/test_jit.py
Labels: Review effort 2/5

#165 DUPLO-34390: Modified jit update_kubeconfig and update_aws_config ensuring parent directories exists
  CHANGELOG.md
  src/duplo_resource/jit.py
  src/tests/test_jit.py
Labels: Review effort 2/5

#168 removing schedulingpriority if set to 0
  CHANGELOG.md
  src/duplo_resource/batch_definition.py
Labels: Review effort 2/5

#169 Revert "updated jit update_aws_config"
  src/duplo_resource/jit.py
  src/tests/test_jit.py
Labels: Review effort 3/5

#170 Revert "Revert "updated jit update_aws_config""
  src/duplo_resource/jit.py
  src/tests/test_jit.py
Labels: Review effort 3/5

#172 Duplo 34549 updating a service and waiting issue with hpa kelly ferrone
  CHANGELOG.md
  src/duplo_resource/service.py
  src/duplocloud/client.py
  src/duplocloud/errors.py
  src/duplocloud/resource.py
  src/tests/data/service.yaml
  src/tests/test_errors.py
Labels: Review effort 4/5

#167 enable redirect based interactive logins
  CHANGELOG.md
  src/duplocloud/client.py
  src/duplocloud/server.py
Labels: Possible security concern, Review effort 3/5

#173 DUPLO-33022: AI Helpdesk Ticket creation & send AI message commands
  CHANGELOG.md
  pyproject.toml
  src/duplo_resource/ai.py
  src/duplocloud/args.py
  src/tests/data/ticket.yaml
  src/tests/test_ai.py
Labels: Review effort 3/5
